schema_version: 1

context:
  name: pystencils-autodiff
  version: 0.3.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pystencils_autodiff-${{ version }}.tar.gz
  sha256: 7ab2dc27bd3a173367fcbc6b9a91c5fa85193119706160d1f731d6ae11ab22e4

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyscaffold >=3.2a0,<3.3a0
    - python ${{ python_min }}.*
    - setuptools <81
  run:
    - jinja2
    - numpy
    - p-tqdm >=1.3
    - pystencils >=0.2.8
    - python >=${{ python_min }}
    - stringcase
    - sympy >=0.5
    - tqdm
    - pycuda

tests:
  - python:
      imports:
        - pystencils_autodiff
        - pystencils_autodiff.backends
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Automatic differentiation and generation of Torch/Tensorflow operations with pystencils
  description: |
    This repo adds automatic differentiation to pystencils.
  homepage: https://i10git.cs.fau.de/pycodegen/pystencils
  repository: https://i10git.cs.fau.de/pycodegen/pystencils
  documentation: https://pystencils-autodiff.readthedocs.io/

extra:
  recipe-maintainers:
    - jan-janssen
